### ISSUE TITLE
Missing PNG's for icons

### ISSUE THREAD

**Issue by ryanhestin** [kokarn/division-item-display#5]
I noticed some are missing and would like to help fill in the gaps.

How did you go about making the png's for the various icons? Ideally I can match the process so they all look similar. Was going to use a color meter to get the background of a simple screen cap and remove all of that color. Should that do the trick?

**Comment by kokarn** [comment]
Should be fine. The only icons i've got so far are items i've found on websites so any process should work.

EDIT: Also, this should be a duplicate of #1 right?

**Comment by ryanhestin** [comment]
Yup, it is.
